# Generated by Django 4.0.3 on 2023-06-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_comment_modify_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modify_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
