# Generated by Django 4.0.3 on 2023-06-04 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0008_alter_comment_modify_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer_comment_voter',
            field=models.ManyToManyField(related_name='voter_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='question_comment_voter',
            field=models.ManyToManyField(related_name='voter_question_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
